# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 淡泊明志，宁静致远
brief-intro: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://28723249.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
email: guoguanfei@gmail.com
github_username: 28723249
twitter_username: 
facebook_username: 
weibo_username: 
zhihu_username: 
linkedIn_username: guoguanfei

description_footer: 学习经历，人生感悟。

# comments
# 三种评论方式，任选一个即可
duoshuo_shortname: 
disqus_shortname:
# Valine不使用shortname，该属性仅用作判断条件，随便填
valine_shortname: guoguanfei

# statistic analysis
# 百度统计 id，将统计代码替换为自己的百度统计id
# 即hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
baidu_tongji_id: f3dff688cb4fb4a144d5460cc6ef235b
google_analytics_id: 

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
tag_dir: tag/
category_dir: category/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
